version: "3.8"
services:
  frontend:
    build:
      context: ./
    networks:
      - csm-network
    depends_on:
      - nginx
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:1.19.0-alpine
    networks:
      - csm-network
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  csm-network:
    name: csm-network
    external: true
