version: "3.8"
services:
  frontend:
    build:
      context: ./
    depends_on:
      - nginx
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/sites-available/www.djcsm.studio.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
  
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      # - ./certbot/certs:/etc/letsencrypt/:ro
    # command: "certonly --webroot -w /var/www/certbot/ --dry-run -d www.djcsm.studio -d djcsm.studio --email
